local BattlepassData = {}
BattlepassData.EasyMaxLevel = 10
BattlepassData.EasyMultiplier = 5
BattlepassData.HardExponent = 1.7

BattlepassData.EndsIn = DateTime.fromLocalTime(2025,6,1).UnixTimestamp

BattlepassData.BattlepassName = "Pixel Pass"

BattlepassData.LevelData = {
	[1] = {
		["Regular"] = {
			Items = {
				PotentialKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				PotentialKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[2] = {
		["Regular"] = {
			Items = {
				FrostKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				FrostKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[3] = {
		["Regular"] = {
			Items = {
				Redstone = 1,
			},
		},
		["Premium"] = {
			Items = {
				Redstone = 5,
			},
		},
		["Exp"] = 1250

	},
	[4] = {
		["Regular"] = {
			Currencies = {
				Gems = 500,
			},
		},
		["Premium"] = {
			Currencies = {
				Gems = 1000,
			},
		},
		["Exp"] = 1250

	},
	[5] = {
		["Regular"] = {
			Items = {
				TraitCrystal = 1,
			},
		},
		["Premium"] = {
			Items = {
				TraitCrystal = 3,
			},
		},
		["Exp"] = 1250

	},
	[6] = {
		["Regular"] = {
			Currencies = {
				Gems = 500,
			},
		},
		["Premium"] = {
			Currencies = {
				Gems = 1000,
			},
		},
		["Exp"] = 1250

	},
	[7] = {
		["Regular"] = {
			Currencies = {
				Gold = 2750,
			},
		},
		["Premium"] = {
			Currencies = {
				Gold = 7500,
			},
		},
		["Exp"] = 1250

	},
	[8] = {
		["Regular"] = {
			Items = {
				Redstone = 1,
			},
		},
		["Premium"] = {
			Items = {
				Redstone = 5,
			},
		},
		["Exp"] = 1250

	},
	[9] = {
		["Regular"] = {
			Items = {
				PotentialKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				PotentialKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[10] = {
		["Regular"] = {
			Items = {
				FrostKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				FrostKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[11] = {
		["Regular"] = {
			Items = {
				TraitCrystal = 1,
			},
		},
		["Premium"] = {
			Items = {
				TraitCrystal = 3,
			},
		},
		["Exp"] = 1250

	},
	[12] = {
		["Regular"] = {
			Currencies = {
				Gems = 500,
			},
		},
		["Premium"] = {
			Currencies = {
				Gems = 1000,
			},
		},
		["Exp"] = 1250

	},
	[13] = {
		["Regular"] = {
			Items = {
				Redstone = 1,
			},
		},
		["Premium"] = {
			Items = {
				Redstone = 5,
			},
		},
		["Exp"] = 1250

	},
	[14] = {
		["Regular"] = {
			Items = {
				PotentialKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				PotentialKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[15] = {
		["Regular"] = {
			Currencies = {
				Gems = 500,
			},
		},
		["Premium"] = {
			Currencies = {
				Gems = 1000,
			},
		},
		["Exp"] = 1250

	},
	[16] = {
		["Regular"] = {
			Currencies = {
				Gold = 3250,
			},
		},
		["Premium"] = {
			Currencies = {
				Gold = 8500,
			},
		},
		["Exp"] = 1250

	},
	[17] = {
		["Regular"] = {
			Items = {
				PotentialKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				PotentialKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[18] = {
		["Regular"] = {
			Items = {
				TraitCrystal = 2,
			},
		},
		["Premium"] = {
			Items = {
				TraitCrystal = 3,
			},
		},
		["Exp"] = 1250

	},
	[19] = {
		["Regular"] = {
			Items = {
				FrostKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				FrostKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[20] = {
		["Regular"] = {
			Currencies = {
				Gems = 500,
			},
		},
		["Premium"] = {
			Currencies = {
				Gems = 1000,
			},
		},
		["Exp"] = 1250

	},
	[21] = {
		["Regular"] = {
			Items = {
				TraitCrystal = 2,
			},
		},
		["Premium"] = {
			Items = {
				TraitCrystal = 3,
			},
		},
		["Exp"] = 1250

	},
	[22] = {
		["Regular"] = {
			Items = {
				PotentialKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				PotentialKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[23] = {
		["Regular"] = {
			Currencies = {
				Gold = 3750,
			},
		},
		["Premium"] = {
			Currencies = {
				Gold = 10_000,
			},
		},
		["Exp"] = 1250

	},
	[24] = {
		["Regular"] = {
			Items = {
				TraitCrystal = 2,
			},
		},
		["Premium"] = {
			Items = {
				TraitCrystal = 6,
			},
		},
		["Exp"] = 1250

	},
	[25] = {

		["Regular"] = {
			Units = {
				['Brook'] = 1
			},
		},
		["Premium"] = {
			ShinyUnits = {
				['Brook'] = 1
			}
		},
		["Exp"] = 1250

	},
	[26] = {
		["Regular"] = {
			Items = {
				PotentialKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				PotentialKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[27] = {
		["Regular"] = {
			Items = {
				FrostKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				FrostKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[28] = {
		["Regular"] = {
			Items = {
				Redstone = 1,
			},
		},
		["Premium"] = {
			Items = {
				Redstone = 5,
			},
		},
		["Exp"] = 1250

	},
	[29] = {
		["Regular"] = {
			Currencies = {
				Gems = 500,
			},
		},
		["Premium"] = {
			Currencies = {
				Gems = 1000,
			},
		},
		["Exp"] = 1250

	},
	[30] = {
		["Regular"] = {
			Items = {
				TraitCrystal = 1,
			},
		},
		["Premium"] = {
			Items = {
				TraitCrystal = 3,
			},
		},
		["Exp"] = 1250

	},
	[31] = {
		["Regular"] = {
			Currencies = {
				Gems = 500,
			},
		},
		["Premium"] = {
			Currencies = {
				Gems = 1000,
			},
		},
		["Exp"] = 1250

	},
	[32] = {
		["Regular"] = {
			Currencies = {
				Gold = 2750,
			},
		},
		["Premium"] = {
			Currencies = {
				Gold = 7500,
			},
		},
		["Exp"] = 1250

	},
	[33] = {
		["Regular"] = {
			Items = {
				Redstone = 1,
			},
		},
		["Premium"] = {
			Items = {
				Redstone = 5,
			},
		},
		["Exp"] = 1250

	},
	[34] = {
		["Regular"] = {
			Items = {
				PotentialKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				PotentialKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[35] = {
		["Regular"] = {
			Items = {
				FrostKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				FrostKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[36] = {
		["Regular"] = {
			Items = {
				TraitCrystal = 1,
			},
		},
		["Premium"] = {
			Items = {
				TraitCrystal = 3,
			},
		},
		["Exp"] = 1250

	},
	[37] = {
		["Regular"] = {
			Currencies = {
				Gems = 500,
			},
		},
		["Premium"] = {
			Currencies = {
				Gems = 1000,
			},
		},
		["Exp"] = 1250

	},
	[38] = {
		["Regular"] = {
			Items = {
				Redstone = 1,
			},
		},
		["Premium"] = {
			Items = {
				Redstone = 5,
			},
		},
		["Exp"] = 1250

	},
	[39] = {
		["Regular"] = {
			Items = {
				PotentialKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				PotentialKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[40] = {
		["Regular"] = {
			Currencies = {
				Gems = 500,
			},
		},
		["Premium"] = {
			Currencies = {
				Gems = 1000,
			},
		},
		["Exp"] = 1250

	},
	[41] = {
		["Regular"] = {
			Currencies = {
				Gold = 3250,
			},
		},
		["Premium"] = {
			Currencies = {
				Gold = 8500,
			},
		},
		["Exp"] = 1250

	},
	[42] = {
		["Regular"] = {
			Items = {
				PotentialKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				PotentialKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[43] = {
		["Regular"] = {
			Items = {
				TraitCrystal = 2,
			},
		},
		["Premium"] = {
			Items = {
				TraitCrystal = 3,
			},
		},
		["Exp"] = 1250

	},
	[44] = {
		["Regular"] = {
			Items = {
				FrostKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				FrostKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[45] = {
		["Regular"] = {
			Currencies = {
				Gems = 500,
			},
		},
		["Premium"] = {
			Currencies = {
				Gems = 1000,
			},
		},
		["Exp"] = 1250

	},
	[46] = {
		["Regular"] = {
			Items = {
				TraitCrystal = 2,
			},
		},
		["Premium"] = {
			Items = {
				TraitCrystal = 3,
			},
		},
		["Exp"] = 1250

	},
	[47] = {
		["Regular"] = {
			Items = {
				PotentialKey = 2,
			},
		},
		["Premium"] = {
			Items = {
				PotentialKey = 6,
			},
		},
		["Exp"] = 1250

	},
	[48] = {
		["Regular"] = {
			Currencies = {
				Gold = 3750,
			},
		},
		["Premium"] = {
			Currencies = {
				Gold = 10_000,
			},
		},
		["Exp"] = 1250

	},
	[49] = {
		["Regular"] = {
			Items = {
				TraitCrystal = 12,
			},
		},
		["Premium"] = {
			Items = {
				TraitCrystal = 6,
			},
		},
		["Exp"] = 1250

	},
	[50] = {

		["Regular"] = {
			Units = {
				['Buggy'] = 1
			},
		},
		["Premium"] = {
			ShinyUnits = {
				['Buggy'] = 1
			}
		},
		["Exp"] = 1250

	}
}



function BattlepassData:CalculateExp(level: number)
	
	if BattlepassData.LevelData[level] then
		return BattlepassData.LevelData[level].Exp
	end
end



function BattlepassData:CalculateTotalExp(level: number?)
	if not level then level = #BattlepassData.LevelData end
	level = math.clamp(level,0,#BattlepassData.LevelData)
	local totalExp = 0
	for i=1, level do
		totalExp += BattlepassData:CalculateExp(i)
	end
	return totalExp
end

return BattlepassData