return {
	RowRewards = {
		[1] = {
			Currencies = {
				Gems = 300,
				["New Year Coin"] = 150
			},
			Items = {
				TraitCrystal = 1
			}
		};
		[2] = {
			Currencies = {
				Gems = 400,
				["New Year Coin"] = 300
			},
			Items = {
				TraitCrystal = 2
			}
		};
		[3] = {
			Currencies = {
				Gems = 500,
				["New Year Coin"] = 450
			},
			Items = {
				TraitCrystal = 3
			}
		};
		[4] = {
			Currencies = {
				Gems = 600,
				["New Year Coin"] = 600
			},
			Items = {
				TraitCrystal = 4
			}
		};
		[5] = {
			Currencies = {
				Gems = 700,
				["New Year Coin"] = 750
			},
			Items = {
				TraitCrystal = 5
			}
		};
		[6] = {
			Currencies = {
				Gems = 800,
				["New Year Coin"] = 900
			},
			Items = {
				TraitCrystal = 6
			}
		};
		[7] = {
			Currencies = {
				Gems = 900,
				["New Year Coin"] = 1050
			},
			Items = {
				TraitCrystal = 7
			}
		};
		[8] = {
			Currencies = {
				Gems = 1000,
				["New Year Coin"] = 1200
			},
			Items = {
				TraitCrystal = 8
			}
		};
		[9] = {
			Units = {
				Sakura = 1
			}
		}
	}
	
}